name : Dev Deployment 

on: push:
    branches: main

jobs:

  redeployment : 
    name : Redeploy FE

  build:
    runs-on: ubuntu-latest
    steps : |
     name : ssh into mechine
     run : |
      echo ${{secrets.SSH_PRIVATE}} &> ~/ssh_key
      ssh -i ~/ssh_key harshit@136.111.126.165
      cd Book-my-show/
      pnpm install
      pnpm run build
      pm2 restart fe-server
      pm2 restart http-server
      pm2 restart ws-server


     
